from convert_save_files import find_subcities_convert2csv_save
from DataProcessing.data_preprocessing import read_folder_path_and_preprocess


MAIN_FOLDER_PATH = '/home/tahir/Documents/DataScience/HavaKalitesiAnomaliTespiti/RawData'

find_subcities_convert2csv_save(MAIN_FOLDER_PATH)

read_folder_path_and_preprocess()
